const galleryImages = [
  {
    imageSml: 'gallery-preview-01.jpg',
    imageSml2x: 'gallery-preview-01@2x.jpg',
    imageLg: 'gallery-image-01.jpg',
    imageLg2x: 'gallery-image-01@2x.jpg',
    alt: 'Shear Madness Hair Style example 01',
  },
  {
    imageSml: 'gallery-preview-02.jpg',
    imageSml2x: 'gallery-preview-02@2x.jpg',
    imageLg: 'gallery-image-02.jpg',
    imageLg2x: 'gallery-image-02@2x.jpg',
    alt: 'Shear Madness Hair Style example 02',
  },
  {
    imageSml: 'gallery-preview-03.jpg',
    imageSml2x: 'gallery-preview-03@2x.jpg',
    imageLg: 'gallery-image-03.jpg',
    imageLg2x: 'gallery-image-03@2x.jpg',
    alt: 'Shear Madness Hair Style example 03',
  },
  {
    imageSml: 'gallery-preview-04.jpg',
    imageSml2x: 'gallery-preview-04@2x.jpg',
    imageLg: 'gallery-image-04.jpg',
    imageLg2x: 'gallery-image-04@2x.jpg',
    alt: 'Shear Madness Hair Style example 04',
  },
  {
    imageSml: 'gallery-preview-05.jpg',
    imageSml2x: 'gallery-preview-05@2x.jpg',
    imageLg: 'gallery-image-05.jpg',
    imageLg2x: 'gallery-image-05@2x.jpg',
    alt: 'Shear Madness Hair Style example 05',
  },
  {
    imageSml: 'gallery-preview-06.jpg',
    imageSml2x: 'gallery-preview-06@2x.jpg',
    imageLg: 'gallery-image-06.jpg',
    imageLg2x: 'gallery-image-06@2x.jpg',
    alt: 'Shear Madness Hair Style example 06',
  },
  {
    imageSml: 'gallery-preview-07.jpg',
    imageSml2x: 'gallery-preview-07@2x.jpg',
    imageLg: 'gallery-image-07.jpg',
    imageLg2x: 'gallery-image-07@2x.jpg',
    alt: 'Shear Madness Hair Style example 07',
  },
  {
    imageSml: 'gallery-preview-08.jpg',
    imageSml2x: 'gallery-preview-08@2x.jpg',
    imageLg: 'gallery-image-08.jpg',
    imageLg2x: 'gallery-image-08@2x.jpg',
    alt: 'Shear Madness Hair Style example 08',
  },
  {
    imageSml: 'gallery-preview-09.jpg',
    imageSml2x: 'gallery-preview-09@2x.jpg',
    imageLg: 'gallery-image-09.jpg',
    imageLg2x: 'gallery-image-09@2x.jpg',
    alt: 'Shear Madness Hair Style example 09',
  },
  {
    imageSml: 'gallery-preview-10.jpg',
    imageSml2x: 'gallery-preview-10@2x.jpg',
    imageLg: 'gallery-image-10.jpg',
    imageLg2x: 'gallery-image-10@2x.jpg',
    alt: 'Shear Madness Hair Style example 10',
  },
  {
    imageSml: 'gallery-preview-11.jpg',
    imageSml2x: 'gallery-preview-11@2x.jpg',
    imageLg: 'gallery-image-11.jpg',
    imageLg2x: 'gallery-image-11@2x.jpg',
    alt: 'Shear Madness Hair Style example 11',
  },
  {
    imageSml: 'gallery-preview-12.jpg',
    imageSml2x: 'gallery-preview-12@2x.jpg',
    imageLg: 'gallery-image-12.jpg',
    imageLg2x: 'gallery-image-12@2x.jpg',
    alt: 'Shear Madness Hair Style example 12',
  },
  {
    imageSml: 'gallery-preview-13.jpg',
    imageSml2x: 'gallery-preview-13@2x.jpg',
    imageLg: 'gallery-image-13.jpg',
    imageLg2x: 'gallery-image-13@2x.jpg',
    alt: 'Shear Madness Hair Style example 13',
  },
  {
    imageSml: 'gallery-preview-14.jpg',
    imageSml2x: 'gallery-preview-14@2x.jpg',
    imageLg: 'gallery-image-14.jpg',
    imageLg2x: 'gallery-image-14@2x.jpg',
    alt: 'Shear Madness Hair Style example 14',
  },
  {
    imageSml: 'gallery-preview-15.jpg',
    imageSml2x: 'gallery-preview-15@2x.jpg',
    imageLg: 'gallery-image-15.jpg',
    imageLg2x: 'gallery-image-15@2x.jpg',
    alt: 'Shear Madness Hair Style example 15',
  },
  {
    imageSml: 'gallery-preview-16.jpg',
    imageSml2x: 'gallery-preview-16@2x.jpg',
    imageLg: 'gallery-image-16.jpg',
    imageLg2x: 'gallery-image-16@2x.jpg',
    alt: 'Shear Madness Hair Style example 16',
  },
  {
    imageSml: 'gallery-preview-17.jpg',
    imageSml2x: 'gallery-preview-17@2x.jpg',
    imageLg: 'gallery-image-17.jpg',
    imageLg2x: 'gallery-image-17@2x.jpg',
    alt: 'Shear Madness Hair Style example 17',
  },
  {
    imageSml: 'gallery-preview-18.jpg',
    imageSml2x: 'gallery-preview-18@2x.jpg',
    imageLg: 'gallery-image-18.jpg',
    imageLg2x: 'gallery-image-18@2x.jpg',
    alt: 'Shear Madness Hair Style example 18',
  },
  {
    imageSml: 'gallery-preview-19.jpg',
    imageSml2x: 'gallery-preview-19@2x.jpg',
    imageLg: 'gallery-image-19.jpg',
    imageLg2x: 'gallery-image-19@2x.jpg',
    alt: 'Shear Madness Hair Style example 19',
  },
  {
    imageSml: 'gallery-preview-20.jpg',
    imageSml2x: 'gallery-preview-20@2x.jpg',
    imageLg: 'gallery-image-20.jpg',
    imageLg2x: 'gallery-image-20@2x.jpg',
    alt: 'Shear Madness Hair Style example 20',
  },
  {
    imageSml: 'gallery-preview-21.jpg',
    imageSml2x: 'gallery-preview-21@2x.jpg',
    imageLg: 'gallery-image-21.jpg',
    imageLg2x: 'gallery-image-21@2x.jpg',
    alt: 'Shear Madness Hair Style example 21',
  },
  {
    imageSml: 'gallery-preview-22.jpg',
    imageSml2x: 'gallery-preview-22@2x.jpg',
    imageLg: 'gallery-image-22.jpg',
    imageLg2x: 'gallery-image-22@2x.jpg',
    alt: 'Shear Madness Hair Style example 22',
  },
  {
    imageSml: 'gallery-preview-23.jpg',
    imageSml2x: 'gallery-preview-23@2x.jpg',
    imageLg: 'gallery-image-23.jpg',
    imageLg2x: 'gallery-image-23@2x.jpg',
    alt: 'Shear Madness Hair Style example 23',
  },
  {
    imageSml: 'gallery-preview-24.jpg',
    imageSml2x: 'gallery-preview-24@2x.jpg',
    imageLg: 'gallery-image-24.jpg',
    imageLg2x: 'gallery-image-24@2x.jpg',
    alt: 'Shear Madness Hair Style example 24',
  },
]

export default galleryImages
